import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased text-slate-900">
        {/* Decorative gradient “light” behind content */}
        <div className="pointer-events-none fixed inset-0 -z-10">
          {/* big blurred gradient blob */}
          <div className="absolute left-1/2 top-[-10%] h-[40rem] w-[40rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle_at_center,_rgba(196,181,253,.35),_transparent_60%)] blur-3xl" />
        </div>

        {/* Content container: roomy, centered */}
        <div className="mx-auto w-full max-w-5xl px-6 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}